_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: b61c2ce6-c184-4d4c-93d5-876163731a56
name: 'Module3 - Test'
mail: tester@gmail.com
slogan: ''
page:
  403: /node/22
  404: /node/21
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
